# Generated by Django 2.1.7 on 2019-03-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='area_knowledge',
            field=models.CharField(blank=True, max_length=50, verbose_name='area of knowledge'),
        ),
        migrations.AddField(
            model_name='account',
            name='baptism',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'Not')], default=None, null=True, verbose_name='baptism'),
        ),
        migrations.AddField(
            model_name='account',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AddField(
            model_name='account',
            name='civil_status',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Other')], default=None, null=True, verbose_name='civil status'),
        ),
        migrations.AddField(
            model_name='account',
            name='educational_level',
            field=models.IntegerField(choices=[(1, 'Primary Student'), (2, 'Bachiller student'), (3, 'College student'), (4, 'Technician / Technology'), (5, 'Professional'), (6, 'Specialist / Master in course'), (7, 'Specialist / Master graduate')], default=None, null=True, verbose_name='educational level'),
        ),
        migrations.AddField(
            model_name='account',
            name='interests',
            field=models.CharField(blank=True, max_length=50, verbose_name='my greatest passion is'),
        ),
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(blank=True, max_length=50, verbose_name='school'),
        ),
    ]
