# Generated by Django 2.1.7 on 2019-03-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190314_0324'),
        ('accounts', '0002_account_points'),
    ]

    operations = [
    ]
