# Generated by Django 2.1.7 on 2019-04-03 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_code_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='qr',
            field=models.ImageField(null=True, upload_to='qr'),
        ),
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
